"""Opt-in price-volume factors with characteristic names.

Nearly identical window variants are omitted. Formulas that need a benchmark
index or Fama-French factors, and formula strings that are truncated, are omitted.
"""

PRICE_VOLUME_CATALOG: dict[str, dict] = {
    'log_volume_change_intraday_return_rank_corr': {
        'formula': '(-1*CORR(RANK(DELTA(LOG(VOLUME),1)),RANK(((CLOSE-OPEN)/OPEN)),6))',
        'description': 'log volume change intraday return rank corr',
        'columns': ['close', 'open', 'volume'],
        'warmup_bars': 6,
        'source_id': 1,
    },
    'close_location_change': {
        'formula': '(-1*DELTA((((CLOSE-LOW)-(HIGH-CLOSE))/(HIGH-LOW)),1))',
        'description': 'close location change',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 1,
        'source_id': 2,
    },
    'directional_gap_sum': {
        'formula': 'SUM((CLOSE=DELAY(CLOSE,1)?0:CLOSE-(CLOSE>DELAY(CLOSE,1)?MIN(LOW,DELAY(CLOSE,1)):MAX(HIGH,DELAY(CLOSE,1)))),6)',
        'description': 'directional gap sum',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 6,
        'source_id': 3,
    },
    'mean_band_volume_state': {
        'formula': '((((SUM(CLOSE,8)/8)+STD(CLOSE,8))<(SUM(CLOSE,2)/2))?(-1*1):(((SUM(CLOSE,2)/2)<((SUM(CLOSE,8)/8)-STD(CLOSE,8)))?1:(((1<(VOLUME/MEAN(VOLUME,20)))|((VOLUME/MEAN(VOLUME,20))==1))?1:(-1*1))))',
        'description': 'mean band volume state',
        'columns': ['close', 'volume'],
        'warmup_bars': 20,
        'source_id': 4,
    },
    'volume_high_ts_rank_corr_max': {
        'formula': '(-1*TSMAX(CORR(TSRANK(VOLUME,5),TSRANK(HIGH,5),5),3))',
        'description': 'volume high ts rank corr max',
        'columns': ['high', 'volume'],
        'warmup_bars': 5,
        'source_id': 5,
    },
    'weighted_open_high_change_rank': {
        'formula': '(RANK(SIGN(DELTA((((OPEN*0.85)+(HIGH*0.15))),4)))*-1)',
        'description': 'weighted open high change rank',
        'columns': ['high', 'open'],
        'warmup_bars': 4,
        'source_id': 6,
    },
    'rank_volume_vwap_3d': {
        'formula': '((RANK(MAX((VWAP-CLOSE),3))+RANK(MIN((VWAP-CLOSE),3)))*RANK(DELTA(VOLUME,3)))',
        'description': 'rank volume vwap 3d',
        'columns': ['close', 'volume'],
        'warmup_bars': 3,
        'source_id': 7,
    },
    'rank_vwap_high_4d': {
        'formula': 'RANK(DELTA(((((HIGH+LOW)/2)*0.2)+(VWAP*0.8)),4)*-1)',
        'description': 'rank vwap high 4d',
        'columns': ['high', 'low'],
        'warmup_bars': 4,
        'source_id': 8,
    },
    'smooth_volume_high_7d': {
        'formula': 'SMA(((HIGH+LOW)/2-(DELAY(HIGH,1)+DELAY(LOW,1))/2)*(HIGH-LOW)/VOLUME,7,2)',
        'description': 'smooth volume high 7d',
        'columns': ['high', 'low', 'volume'],
        'warmup_bars': 7,
        'source_id': 9,
    },
    'rank_volatility_return_close_20d': {
        'formula': '(RANK(MAX(((RET<0)?STD(RET,20):CLOSE)^2,5)))',
        'description': 'rank volatility return close 20d',
        'columns': ['close'],
        'warmup_bars': 20,
        'source_id': 10,
    },
    'volume_high_6d': {
        'formula': 'SUM(((CLOSE-LOW)-(HIGH-CLOSE))/(HIGH-LOW)*VOLUME,6)',
        'description': 'volume high 6d',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 6,
        'source_id': 11,
    },
    'rank_vwap_open_10d': {
        'formula': '(RANK((OPEN-(SUM(VWAP,10)/10))))*(-1*(RANK(ABS((CLOSE-VWAP)))))',
        'description': 'rank vwap open 10d',
        'columns': ['close', 'open'],
        'warmup_bars': 10,
        'source_id': 12,
    },
    'geometric_price_vwap_gap': {
        'formula': 'SQRT(HIGH*LOW)-VWAP',
        'description': 'geometric price vwap gap',
        'columns': ['high', 'low'],
        'warmup_bars': 1,
        'source_id': 13,
    },
    'overnight_return': {
        'formula': 'OPEN/DELAY(CLOSE,1)-1',
        'description': 'overnight return',
        'columns': ['close', 'open'],
        'warmup_bars': 1,
        'source_id': 15,
    },
    'corr_smooth_rank_volume_vwap_5d': {
        'formula': '(-1*TSMAX(RANK(CORR(RANK(VOLUME),RANK(VWAP),5)),5))',
        'description': 'corr smooth rank volume vwap 5d',
        'columns': ['volume'],
        'warmup_bars': 5,
        'source_id': 16,
    },
    'rank_vwap_close_15d': {
        'formula': 'RANK((VWAP-MAX(VWAP,15)))^DELTA(CLOSE,5)',
        'description': 'rank vwap close 15d',
        'columns': ['close'],
        'warmup_bars': 15,
        'source_id': 17,
    },
    'close_5d': {
        'formula': '(CLOSE<DELAY(CLOSE,5)?(CLOSE-DELAY(CLOSE,5))/DELAY(CLOSE,5):(CLOSE=DELAY(CLOSE,5)?0:(CLOSE-DELAY(CLOSE,5))/CLOSE))',
        'description': 'close 5d',
        'columns': ['close'],
        'warmup_bars': 5,
        'source_id': 19,
    },
    'close_mean_trend_slope': {
        'formula': 'REGBETA(MEAN(CLOSE,6),SEQUENCE(6))',
        'description': 'close mean trend slope',
        'columns': ['close'],
        'warmup_bars': 6,
        'source_id': 21,
    },
    'smooth_close_12d': {
        'formula': 'SMA(((CLOSE-MEAN(CLOSE,6))/MEAN(CLOSE,6)-DELAY((CLOSE-MEAN(CLOSE,6))/MEAN(CLOSE,6),3)),12,1)',
        'description': 'smooth close 12d',
        'columns': ['close'],
        'warmup_bars': 12,
        'source_id': 22,
    },
    'smooth_volatility_close_100d': {
        'formula': 'SMA((CLOSE>DELAY(CLOSE,1)?STD(CLOSE,20):0),20,1)/(SMA((CLOSE>DELAY(CLOSE,1)?STD(CLOSE,20):0),20,1)+SMA((CLOSE<=DELAY(CLOSE,1)?STD(CLOSE,20):0),20,1))*100',
        'description': 'smooth volatility close 100d',
        'columns': ['close'],
        'warmup_bars': 100,
        'source_id': 23,
    },
    'smooth_close_5d': {
        'formula': 'SMA(CLOSE-DELAY(CLOSE,5),5,1)',
        'description': 'smooth close 5d',
        'columns': ['close'],
        'warmup_bars': 5,
        'source_id': 24,
    },
    'decay_rank_volume_return_250d': {
        'formula': '((-1*RANK((DELTA(CLOSE,7)*(1-RANK(DECAYLINEAR((VOLUME/MEAN(VOLUME,20)),9))))))*(1+RANK(SUM(RET,250))))',
        'description': 'decay rank volume return 250d',
        'columns': ['close', 'volume'],
        'warmup_bars': 250,
        'source_id': 25,
    },
    'corr_vwap_close_230d': {
        'formula': '((((SUM(CLOSE,7)/7)-CLOSE))+((CORR(VWAP,DELAY(CLOSE,5),230))))',
        'description': 'corr vwap close 230d',
        'columns': ['close'],
        'warmup_bars': 230,
        'source_id': 26,
    },
    'weighted_mean_close_100d': {
        'formula': 'WMA((CLOSE-DELAY(CLOSE,3))/DELAY(CLOSE,3)*100+(CLOSE-DELAY(CLOSE,6))/DELAY(CLOSE,6)*100,12)',
        'description': 'weighted mean close 100d',
        'columns': ['close'],
        'warmup_bars': 100,
        'source_id': 27,
    },
    'smooth_high_low_100d': {
        'formula': '3*SMA((CLOSE-TSMIN(LOW,9))/(TSMAX(HIGH,9)-TSMIN(LOW,9))*100,3,1)-2*SMA(SMA((CLOSE-TSMIN(LOW,9))/(MAX(HIGH,9)-TSMAX(LOW,9))*100,3,1),3,1)',
        'description': 'smooth high low 100d',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 100,
        'source_id': 28,
    },
    'volume_close_6d': {
        'formula': '(CLOSE-DELAY(CLOSE,6))/DELAY(CLOSE,6)*VOLUME',
        'description': 'volume close 6d',
        'columns': ['close', 'volume'],
        'warmup_bars': 6,
        'source_id': 29,
    },
    'close_100d': {
        'formula': '(CLOSE-MEAN(CLOSE,12))/MEAN(CLOSE,12)*100',
        'description': 'close 100d',
        'columns': ['close'],
        'warmup_bars': 100,
        'source_id': 31,
    },
    'corr_rank_volume_high_3d': {
        'formula': '(-1*SUM(RANK(CORR(RANK(HIGH),RANK(VOLUME),3)),3))',
        'description': 'corr rank volume high 3d',
        'columns': ['high', 'volume'],
        'warmup_bars': 3,
        'source_id': 32,
    },
    'ts_rank_rank_volume_return_240d': {
        'formula': '((((-1*TSMIN(LOW,5))+DELAY(TSMIN(LOW,5),5))*RANK(((SUM(RET,240)-SUM(RET,20))/220)))*TSRANK(VOLUME,5))',
        'description': 'ts rank rank volume return 240d',
        'columns': ['close', 'low', 'volume'],
        'warmup_bars': 240,
        'source_id': 33,
    },
    'close_12d': {
        'formula': 'MEAN(CLOSE,12)/CLOSE',
        'description': 'close 12d',
        'columns': ['close'],
        'warmup_bars': 12,
        'source_id': 34,
    },
    'decay_corr_rank_volume_open_17d': {
        'formula': '(MIN(RANK(DECAYLINEAR(DELTA(OPEN,1),15)),RANK(DECAYLINEAR(CORR((VOLUME),((OPEN*0.65)+(OPEN*0.35)),17),7)))*-1)',
        'description': 'decay corr rank volume open 17d',
        'columns': ['open', 'volume'],
        'warmup_bars': 17,
        'source_id': 35,
    },
    'corr_rank_volume_vwap_6d': {
        'formula': 'RANK(SUM(CORR(RANK(VOLUME),RANK(VWAP),6),2))',
        'description': 'corr rank volume vwap 6d',
        'columns': ['volume'],
        'warmup_bars': 6,
        'source_id': 36,
    },
    'rank_return_open_10d': {
        'formula': '(-1*RANK(((SUM(OPEN,5)*SUM(RET,5))-DELAY((SUM(OPEN,5)*SUM(RET,5)),10))))',
        'description': 'rank return open 10d',
        'columns': ['close', 'open'],
        'warmup_bars': 10,
        'source_id': 37,
    },
    'high_20d': {
        'formula': '(((SUM(HIGH,20)/20)<HIGH)?(-1*DELTA(HIGH,2)):0)',
        'description': 'high 20d',
        'columns': ['high'],
        'warmup_bars': 20,
        'source_id': 38,
    },
    'decay_corr_rank_volume_vwap_180d': {
        'formula': '((RANK(DECAYLINEAR(DELTA((CLOSE),2),8))-RANK(DECAYLINEAR(CORR(((VWAP*0.3)+(OPEN*0.7)),SUM(MEAN(VOLUME,180),37),14),12)))*-1)',
        'description': 'decay corr rank volume vwap 180d',
        'columns': ['close', 'open', 'volume'],
        'warmup_bars': 180,
        'source_id': 39,
    },
    'up_down_volume_ratio': {
        'formula': 'SUM((CLOSE>DELAY(CLOSE,1)?VOLUME:0),26)/SUM((CLOSE<=DELAY(CLOSE,1)?VOLUME:0),26)*100',
        'description': 'up down volume ratio',
        'columns': ['close', 'volume'],
        'warmup_bars': 100,
        'source_id': 40,
    },
    'rank_vwap_5d': {
        'formula': '(RANK(MAX(DELTA((VWAP),3),5))*-1)',
        'description': 'rank vwap 5d',
        'columns': [],
        'warmup_bars': 5,
        'source_id': 41,
    },
    'high_volatility_volume_corr': {
        'formula': '((-1*RANK(STD(HIGH,10)))*CORR(HIGH,VOLUME,10))',
        'description': 'high volatility volume corr',
        'columns': ['high', 'volume'],
        'warmup_bars': 10,
        'source_id': 42,
    },
    'signed_volume_sum': {
        'formula': 'SUM((CLOSE>DELAY(CLOSE,1)?VOLUME:(CLOSE<DELAY(CLOSE,1)?-VOLUME:0)),6)',
        'description': 'signed volume sum',
        'columns': ['close', 'volume'],
        'warmup_bars': 6,
        'source_id': 43,
    },
    'decay_corr_ts_rank_volume_vwap_15d': {
        'formula': '(TSRANK(DECAYLINEAR(CORR(((LOW)),MEAN(VOLUME,10),7),6),4)+TSRANK(DECAYLINEAR(DELTA((VWAP),3),10),15))',
        'description': 'decay corr ts rank volume vwap 15d',
        'columns': ['low', 'volume'],
        'warmup_bars': 15,
        'source_id': 44,
    },
    'corr_rank_volume_vwap_150d': {
        'formula': '(RANK(DELTA((((CLOSE*0.6)+(OPEN*0.4))),1))*RANK(CORR(VWAP,MEAN(VOLUME,150),15)))',
        'description': 'corr rank volume vwap 150d',
        'columns': ['close', 'open', 'volume'],
        'warmup_bars': 150,
        'source_id': 45,
    },
    'close_24d': {
        'formula': '(MEAN(CLOSE,3)+MEAN(CLOSE,6)+MEAN(CLOSE,12)+MEAN(CLOSE,24))/(4*CLOSE)',
        'description': 'close 24d',
        'columns': ['close'],
        'warmup_bars': 24,
        'source_id': 46,
    },
    'smooth_high_low_100d_9': {
        'formula': 'SMA((TSMAX(HIGH,6)-CLOSE)/(TSMAX(HIGH,6)-TSMIN(LOW,6))*100,9,1)',
        'description': 'smooth high low 100d 9',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 100,
        'source_id': 47,
    },
    'rank_volume_close_20d': {
        'formula': '(-1*((RANK(((SIGN((CLOSE-DELAY(CLOSE,1)))+SIGN((DELAY(CLOSE,1)-DELAY(CLOSE,2))))+SIGN((DELAY(CLOSE,2)-DELAY(CLOSE,3))))))*SUM(VOLUME,5))/SUM(VOLUME,20))',
        'description': 'rank volume close 20d',
        'columns': ['close', 'volume'],
        'warmup_bars': 20,
        'source_id': 48,
    },
    'down_shadow_pressure': {
        'formula': 'SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)/(SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)+SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12))',
        'description': 'down shadow pressure',
        'columns': ['high', 'low'],
        'warmup_bars': 12,
        'source_id': 49,
    },
    'high_low_12d': {
        'formula': 'SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)/(SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)+SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12))-SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)/(SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)+SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12))',
        'description': 'high low 12d',
        'columns': ['high', 'low'],
        'warmup_bars': 12,
        'source_id': 50,
    },
    'up_shadow_pressure': {
        'formula': 'SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)/(SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)+SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12))',
        'description': 'up shadow pressure',
        'columns': ['high', 'low'],
        'warmup_bars': 12,
        'source_id': 51,
    },
    'high_low_100d': {
        'formula': 'SUM(MAX(0,HIGH-DELAY((HIGH+LOW+CLOSE)/3,1)),26)/SUM(MAX(0,DELAY((HIGH+LOW+CLOSE)/3,1)-LOW),26)*100',
        'description': 'high low 100d',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 100,
        'source_id': 52,
    },
    'up_day_share': {
        'formula': 'COUNT(CLOSE>DELAY(CLOSE,1),12)/12*100',
        'description': 'up day share',
        'columns': ['close'],
        'warmup_bars': 100,
        'source_id': 53,
    },
    'corr_rank_volatility_open_close_10d': {
        'formula': '(-1*RANK((STD(ABS(CLOSE-OPEN),10)+(CLOSE-OPEN))+CORR(CLOSE,OPEN,10)))',
        'description': 'corr rank volatility open close 10d',
        'columns': ['close', 'open'],
        'warmup_bars': 10,
        'source_id': 54,
    },
    'open_high_20d': {
        'formula': 'SUM(16*(CLOSE-DELAY(CLOSE,1)+(CLOSE-OPEN)/2+DELAY(CLOSE,1)-DELAY(OPEN,1))/((ABS(HIGH-DELAY(CLOSE,1))>ABS(LOW-DELAY(CLOSE,1))&ABS(HIGH-DELAY(CLOSE,1))>ABS(HIGH-DELAY(LOW,1))?ABS(HIGH-DELAY(CLOSE,1))+ABS(LOW-DELAY(CLOSE,1))/2+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4:(ABS(LOW-DELAY(CLOSE,1))>ABS(HIGH-DELAY(LOW,1))&ABS(LOW-DELAY(CLOSE,1))>ABS(HIGH-DELAY(CLOSE,1))?ABS(LOW-DELAY(CLOSE,1))+ABS(HIGH-DELAY(CLOSE,1))/2+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4:ABS(HIGH-DELAY(LOW,1))+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4)))*MAX(ABS(HIGH-DELAY(CLOSE,1)),ABS(LOW-DELAY(CLOSE,1))),20)',
        'description': 'open high 20d',
        'columns': ['close', 'high', 'low', 'open'],
        'warmup_bars': 20,
        'source_id': 55,
    },
    'corr_rank_volume_open_40d': {
        'formula': '(RANK((OPEN-TSMIN(OPEN,12)))<RANK((RANK(CORR(SUM(((HIGH+LOW)/2),19),SUM(MEAN(VOLUME,40),19),13))^5)))',
        'description': 'corr rank volume open 40d',
        'columns': ['high', 'low', 'open', 'volume'],
        'warmup_bars': 40,
        'source_id': 56,
    },
    'smooth_high_low_100d_3': {
        'formula': 'SMA((CLOSE-TSMIN(LOW,9))/(TSMAX(HIGH,9)-TSMIN(LOW,9))*100,3,1)',
        'description': 'smooth high low 100d 3',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 100,
        'source_id': 57,
    },
    'decay_corr_rank_volume_vwap_80d': {
        'formula': '(MAX(RANK(DECAYLINEAR(DELTA(VWAP,1),12)),RANK(DECAYLINEAR(RANK(CORR((LOW),MEAN(VOLUME,80),8)),17)))*-1)',
        'description': 'decay corr rank volume vwap 80d',
        'columns': ['low', 'volume'],
        'warmup_bars': 80,
        'source_id': 61,
    },
    'corr_rank_volume_high_5d': {
        'formula': '(-1*CORR(HIGH,RANK(VOLUME),5))',
        'description': 'corr rank volume high 5d',
        'columns': ['high', 'volume'],
        'warmup_bars': 5,
        'source_id': 62,
    },
    'smooth_up_close_ratio': {
        'formula': 'SMA(MAX(CLOSE-DELAY(CLOSE,1),0),6,1)/SMA(ABS(CLOSE-DELAY(CLOSE,1)),6,1)*100',
        'description': 'smooth up close ratio',
        'columns': ['close'],
        'warmup_bars': 100,
        'source_id': 63,
    },
    'decay_corr_rank_volume_vwap_60d': {
        'formula': '(MAX(RANK(DECAYLINEAR(CORR(RANK(VWAP),RANK(VOLUME),4),4)),RANK(DECAYLINEAR(MAX(CORR(RANK(CLOSE),RANK(MEAN(VOLUME,60)),4),13),14)))*-1)',
        'description': 'decay corr rank volume vwap 60d',
        'columns': ['close', 'volume'],
        'warmup_bars': 60,
        'source_id': 64,
    },
    'directional_move_balance': {
        'formula': '(SUM(DTM,20)>SUM(DBM,20)?(SUM(DTM,20)-SUM(DBM,20))/SUM(DTM,20):(SUM(DTM,20)=SUM(DBM,20)?0:(SUM(DTM,20)-SUM(DBM,20))/SUM(DBM,20)))',
        'description': 'directional move balance',
        'columns': ['close', 'high', 'low', 'open'],
        'warmup_bars': 20,
        'source_id': 69,
    },
    'amount_volatility': {
        'formula': 'STD(AMOUNT,6)',
        'description': 'amount volatility',
        'columns': ['amount'],
        'warmup_bars': 6,
        'source_id': 70,
    },
    'decay_corr_ts_rank_volume_vwap_30d': {
        'formula': '((TSRANK(DECAYLINEAR(DECAYLINEAR(CORR((CLOSE),VOLUME,10),16),4),5)-RANK(DECAYLINEAR(CORR(VWAP,MEAN(VOLUME,30),4),3)))*-1)',
        'description': 'decay corr ts rank volume vwap 30d',
        'columns': ['close', 'volume'],
        'warmup_bars': 30,
        'source_id': 73,
    },
    'corr_rank_volume_vwap_40d': {
        'formula': '(RANK(CORR(SUM(((LOW*0.35)+(VWAP*0.65)),20),SUM(MEAN(VOLUME,40),20),7))+RANK(CORR(RANK(VWAP),RANK(VOLUME),6)))',
        'description': 'corr rank volume vwap 40d',
        'columns': ['low', 'volume'],
        'warmup_bars': 40,
        'source_id': 74,
    },
    'return_per_volume_stability': {
        'formula': 'STD(ABS((CLOSE/DELAY(CLOSE,1)-1))/VOLUME,20)/MEAN(ABS((CLOSE/DELAY(CLOSE,1)-1))/VOLUME,20)',
        'description': 'return per volume stability',
        'columns': ['close', 'volume'],
        'warmup_bars': 20,
        'source_id': 76,
    },
    'decay_corr_rank_volume_vwap_40d': {
        'formula': 'MIN(RANK(DECAYLINEAR(((((HIGH+LOW)/2)+HIGH)-(VWAP+HIGH)),20)),RANK(DECAYLINEAR(CORR(((HIGH+LOW)/2),MEAN(VOLUME,40),3),6)))',
        'description': 'decay corr rank volume vwap 40d',
        'columns': ['high', 'low', 'volume'],
        'warmup_bars': 40,
        'source_id': 77,
    },
    'high_low_12d_12': {
        'formula': '((HIGH+LOW+CLOSE)/3-MEAN((HIGH+LOW+CLOSE)/3,12))/(0.015*MEAN(ABS(CLOSE-MEAN((HIGH+LOW+CLOSE)/3,12)),12))',
        'description': 'high low 12d 12',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 12,
        'source_id': 78,
    },
    'volume_change': {
        'formula': '(VOLUME-DELAY(VOLUME,5))/DELAY(VOLUME,5)*100',
        'description': 'volume change',
        'columns': ['volume'],
        'warmup_bars': 100,
        'source_id': 80,
    },
    'smooth_volume': {
        'formula': 'SMA(VOLUME,21,2)',
        'description': 'smooth volume',
        'columns': ['volume'],
        'warmup_bars': 21,
        'source_id': 81,
    },
    'cov_rank_volume_high_5d': {
        'formula': '(-1*RANK(COVARIANCE(RANK(HIGH),RANK(VOLUME),5)))',
        'description': 'cov rank volume high 5d',
        'columns': ['high', 'volume'],
        'warmup_bars': 5,
        'source_id': 83,
    },
    'ts_rank_rank_volume_close_20d': {
        'formula': '(TSRANK((VOLUME/MEAN(VOLUME,20)),20)*TSRANK((-1*DELTA(CLOSE,7)),8))',
        'description': 'ts rank rank volume close 20d',
        'columns': ['close', 'volume'],
        'warmup_bars': 20,
        'source_id': 85,
    },
    'close_20d': {
        'formula': '((0.25<(((DELAY(CLOSE,20)-DELAY(CLOSE,10))/10)-((DELAY(CLOSE,10)-CLOSE)/10)))?(-1*1):(((((DELAY(CLOSE,20)-DELAY(CLOSE,10))/10)-((DELAY(CLOSE,10)-CLOSE)/10))<0)?1:((-1*1)*(CLOSE-DELAY(CLOSE,1)))))',
        'description': 'close 20d',
        'columns': ['close'],
        'warmup_bars': 20,
        'source_id': 86,
    },
    'decay_ts_rank_rank_vwap_open_11d': {
        'formula': '((RANK(DECAYLINEAR(DELTA(VWAP,4),7))+TSRANK(DECAYLINEAR(((((LOW*0.9)+(LOW*0.1))-VWAP)/(OPEN-((HIGH+LOW)/2))),11),7))*-1)',
        'description': 'decay ts rank rank vwap open 11d',
        'columns': ['high', 'low', 'open'],
        'warmup_bars': 11,
        'source_id': 87,
    },
    'smooth_close_27d': {
        'formula': '2*(SMA(CLOSE,13,2)-SMA(CLOSE,27,2)-SMA(SMA(CLOSE,13,2)-SMA(CLOSE,27,2),10,2))',
        'description': 'smooth close 27d',
        'columns': ['close'],
        'warmup_bars': 27,
        'source_id': 89,
    },
    'corr_rank_volume_vwap_5d': {
        'formula': '(RANK(CORR(RANK(VWAP),RANK(VOLUME),5))*-1)',
        'description': 'corr rank volume vwap 5d',
        'columns': ['volume'],
        'warmup_bars': 5,
        'source_id': 90,
    },
    'corr_rank_volume_low_40d': {
        'formula': '((RANK((CLOSE-MAX(CLOSE,5)))*RANK(CORR((MEAN(VOLUME,40)),LOW,5)))*-1)',
        'description': 'corr rank volume low 40d',
        'columns': ['close', 'low', 'volume'],
        'warmup_bars': 40,
        'source_id': 91,
    },
    'decay_corr_ts_rank_volume_vwap_180d': {
        'formula': '(MAX(RANK(DECAYLINEAR(DELTA(((CLOSE*0.35)+(VWAP*0.65)),2),3)),TSRANK(DECAYLINEAR(ABS(CORR((MEAN(VOLUME,180)),CLOSE,13)),5),15))*-1)',
        'description': 'decay corr ts rank volume vwap 180d',
        'columns': ['close', 'volume'],
        'warmup_bars': 180,
        'source_id': 92,
    },
    'open_low_20d': {
        'formula': 'SUM((OPEN>=DELAY(OPEN,1)?0:MAX((OPEN-LOW),(OPEN-DELAY(OPEN,1)))),20)',
        'description': 'open low 20d',
        'columns': ['low', 'open'],
        'warmup_bars': 20,
        'source_id': 93,
    },
    'smooth_high_low_100d_96': {
        'formula': 'SMA(SMA((CLOSE-TSMIN(LOW,9))/(TSMAX(HIGH,9)-TSMIN(LOW,9))*100,3,1),3,1)',
        'description': 'smooth high low 100d 96',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 100,
        'source_id': 96,
    },
    'volume_volatility': {
        'formula': 'STD(VOLUME,10)',
        'description': 'volume volatility',
        'columns': ['volume'],
        'warmup_bars': 10,
        'source_id': 97,
    },
    'close_100d_3': {
        'formula': '((((DELTA((SUM(CLOSE,100)/100),100)/DELAY(CLOSE,100))<0.05)|((DELTA((SUM(CLOSE,100)/100),100)/DELAY(CLOSE,100))==0.05))?(-1*(CLOSE-TSMIN(CLOSE,100))):(-1*DELTA(CLOSE,3)))',
        'description': 'close 100d 3',
        'columns': ['close'],
        'warmup_bars': 100,
        'source_id': 98,
    },
    'cov_rank_volume_close_5d': {
        'formula': '(-1*RANK(COVARIANCE(RANK(CLOSE),RANK(VOLUME),5)))',
        'description': 'cov rank volume close 5d',
        'columns': ['close', 'volume'],
        'warmup_bars': 5,
        'source_id': 99,
    },
    'corr_rank_volume_vwap_37d': {
        'formula': '((RANK(CORR(CLOSE,SUM(MEAN(VOLUME,30),37),15))<RANK(CORR(RANK(((HIGH*0.1)+(VWAP*0.9))),RANK(VOLUME),11)))*-1)',
        'description': 'corr rank volume vwap 37d',
        'columns': ['close', 'high', 'volume'],
        'warmup_bars': 37,
        'source_id': 101,
    },
    'smooth_up_volume_ratio': {
        'formula': 'SMA(MAX(VOLUME-DELAY(VOLUME,1),0),6,1)/SMA(ABS(VOLUME-DELAY(VOLUME,1)),6,1)*100',
        'description': 'smooth up volume ratio',
        'columns': ['volume'],
        'warmup_bars': 100,
        'source_id': 102,
    },
    'days_since_low_share': {
        'formula': '((20-LOWDAY(LOW,20))/20)*100',
        'description': 'days since low share',
        'columns': ['low'],
        'warmup_bars': 100,
        'source_id': 103,
    },
    'corr_rank_volatility_volume_high_20d': {
        'formula': '(-1*(DELTA(CORR(HIGH,VOLUME,5),5)*RANK(STD(CLOSE,20))))',
        'description': 'corr rank volatility volume high 20d',
        'columns': ['close', 'high', 'volume'],
        'warmup_bars': 20,
        'source_id': 104,
    },
    'corr_rank_volume_open_10d': {
        'formula': '(-1*CORR(RANK(OPEN),RANK(VOLUME),10))',
        'description': 'corr rank volume open 10d',
        'columns': ['open', 'volume'],
        'warmup_bars': 10,
        'source_id': 105,
    },
    'rank_open_high_1d': {
        'formula': '(((-1*RANK((OPEN-DELAY(HIGH,1))))*RANK((OPEN-DELAY(CLOSE,1))))*RANK((OPEN-DELAY(LOW,1))))',
        'description': 'rank open high 1d',
        'columns': ['close', 'high', 'low', 'open'],
        'warmup_bars': 1,
        'source_id': 107,
    },
    'corr_rank_volume_vwap_120d': {
        'formula': '((RANK((HIGH-MIN(HIGH,2)))^RANK(CORR((VWAP),(MEAN(VOLUME,120)),6)))*-1)',
        'description': 'corr rank volume vwap 120d',
        'columns': ['high', 'volume'],
        'warmup_bars': 120,
        'source_id': 108,
    },
    'smooth_high_low_10d': {
        'formula': 'SMA(HIGH-LOW,10,2)/SMA(SMA(HIGH-LOW,10,2),10,2)',
        'description': 'smooth high low 10d',
        'columns': ['high', 'low'],
        'warmup_bars': 10,
        'source_id': 109,
    },
    'true_range_balance': {
        'formula': 'SUM(MAX(0,HIGH-DELAY(CLOSE,1)),20)/SUM(MAX(0,DELAY(CLOSE,1)-LOW),20)*100',
        'description': 'true range balance',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 100,
        'source_id': 110,
    },
    'smooth_volume_high_11d': {
        'formula': 'SMA(VOLUME*((CLOSE-LOW)-(HIGH-CLOSE))/(HIGH-LOW),11,2)-SMA(VOLUME*((CLOSE-LOW)-(HIGH-CLOSE))/(HIGH-LOW),4,2)',
        'description': 'smooth volume high 11d',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 11,
        'source_id': 111,
    },
    'close_100d_100': {
        'formula': '(SUM((CLOSE-DELAY(CLOSE,1)>0?CLOSE-DELAY(CLOSE,1):0),12)-SUM((CLOSE-DELAY(CLOSE,1)<0?ABS(CLOSE-DELAY(CLOSE,1)):0),12))/(SUM((CLOSE-DELAY(CLOSE,1)>0?CLOSE-DELAY(CLOSE,1):0),12)+SUM((CLOSE-DELAY(CLOSE,1)<0?ABS(CLOSE-DELAY(CLOSE,1)):0),12))*100',
        'description': 'close 100d 100',
        'columns': ['close'],
        'warmup_bars': 100,
        'source_id': 112,
    },
    'corr_rank_volume_close_20d': {
        'formula': '(-1*((RANK((SUM(DELAY(CLOSE,5),20)/20))*CORR(CLOSE,VOLUME,2))*RANK(CORR(SUM(CLOSE,5),SUM(CLOSE,20),2))))',
        'description': 'corr rank volume close 20d',
        'columns': ['close', 'volume'],
        'warmup_bars': 20,
        'source_id': 113,
    },
    'rank_volume_vwap_5d': {
        'formula': '((RANK(DELAY(((HIGH-LOW)/(SUM(CLOSE,5)/5)),2))*RANK(RANK(VOLUME)))/(((HIGH-LOW)/(SUM(CLOSE,5)/5))/(VWAP-CLOSE)))',
        'description': 'rank volume vwap 5d',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 5,
        'source_id': 114,
    },
    'corr_ts_rank_rank_volume_high_30d': {
        'formula': '(RANK(CORR(((HIGH*0.9)+(CLOSE*0.1)),MEAN(VOLUME,30),10))^RANK(CORR(TSRANK(((HIGH+LOW)/2),4),TSRANK(VOLUME,10),7)))',
        'description': 'corr ts rank rank volume high 30d',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 30,
        'source_id': 115,
    },
    'slope_close_20d': {
        'formula': 'REGBETA(CLOSE,SEQUENCE(20))',
        'description': 'slope close 20d',
        'columns': ['close'],
        'warmup_bars': 20,
        'source_id': 116,
    },
    'ts_rank_rank_volume_return_32d': {
        'formula': '((TSRANK(VOLUME,32)*(1-TSRANK(((CLOSE+HIGH)-LOW),16)))*(1-TSRANK(RET,32)))',
        'description': 'ts rank rank volume return 32d',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 32,
        'source_id': 117,
    },
    'upper_lower_wick_ratio': {
        'formula': 'SUM(HIGH-OPEN,20)/SUM(OPEN-LOW,20)*100',
        'description': 'upper lower wick ratio',
        'columns': ['high', 'low', 'open'],
        'warmup_bars': 100,
        'source_id': 118,
    },
    'decay_corr_ts_rank_volume_vwap_26d': {
        'formula': '(RANK(DECAYLINEAR(CORR(VWAP,SUM(MEAN(VOLUME,5),26),5),7))-RANK(DECAYLINEAR(TSRANK(MIN(CORR(RANK(OPEN),RANK(MEAN(VOLUME,15)),21),9),7),8)))',
        'description': 'decay corr ts rank volume vwap 26d',
        'columns': ['open', 'volume'],
        'warmup_bars': 26,
        'source_id': 119,
    },
    'vwap_close_rank_gap': {
        'formula': '(RANK((VWAP-CLOSE))/RANK((VWAP+CLOSE)))',
        'description': 'vwap close rank gap',
        'columns': ['close'],
        'warmup_bars': 1,
        'source_id': 120,
    },
    'corr_ts_rank_rank_volume_vwap_60d': {
        'formula': '((RANK((VWAP-MIN(VWAP,12)))^TSRANK(CORR(TSRANK(VWAP,20),TSRANK(MEAN(VOLUME,60),2),18),3))*-1)',
        'description': 'corr ts rank rank volume vwap 60d',
        'columns': ['volume'],
        'warmup_bars': 60,
        'source_id': 121,
    },
    'smooth_close_13d': {
        'formula': '(SMA(SMA(SMA(LOG(CLOSE),13,2),13,2),13,2)-DELAY(SMA(SMA(SMA(LOG(CLOSE),13,2),13,2),13,2),1))/DELAY(SMA(SMA(SMA(LOG(CLOSE),13,2),13,2),13,2),1)',
        'description': 'smooth close 13d',
        'columns': ['close'],
        'warmup_bars': 13,
        'source_id': 122,
    },
    'corr_rank_volume_high_60d': {
        'formula': '((RANK(CORR(SUM(((HIGH+LOW)/2),20),SUM(MEAN(VOLUME,60),20),9))<RANK(CORR(LOW,VOLUME,6)))*-1)',
        'description': 'corr rank volume high 60d',
        'columns': ['high', 'low', 'volume'],
        'warmup_bars': 60,
        'source_id': 123,
    },
    'decay_smooth_rank_vwap_close_30d': {
        'formula': '(CLOSE-VWAP)/DECAYLINEAR(RANK(TSMAX(CLOSE,30)),2)',
        'description': 'decay smooth rank vwap close 30d',
        'columns': ['close'],
        'warmup_bars': 30,
        'source_id': 124,
    },
    'decay_corr_rank_volume_vwap_80d_16': {
        'formula': '(RANK(DECAYLINEAR(CORR((VWAP),MEAN(VOLUME,80),17),20))/RANK(DECAYLINEAR(DELTA(((CLOSE*0.5)+(VWAP*0.5)),3),16)))',
        'description': 'decay corr rank volume vwap 80d 16',
        'columns': ['close', 'volume'],
        'warmup_bars': 80,
        'source_id': 125,
    },
    'high_low_3d': {
        'formula': '(CLOSE+HIGH+LOW)/3',
        'description': 'high low 3d',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 3,
        'source_id': 126,
    },
    'high_gap_root_mean_square': {
        'formula': '(MEAN((100*(CLOSE-MAX(CLOSE,12))/(MAX(CLOSE,12)))^2,12))^(1/2)',
        'description': 'high gap root mean square',
        'columns': ['close'],
        'warmup_bars': 12,
        'source_id': 127,
    },
    'volume_high_100d': {
        'formula': '100-(100/(1+SUM(((HIGH+LOW+CLOSE)/3>DELAY((HIGH+LOW+CLOSE)/3,1)?(HIGH+LOW+CLOSE)/3*VOLUME:0),14)/SUM(((HIGH+LOW+CLOSE)/3<DELAY((HIGH+LOW+CLOSE)/3,1)?(HIGH+LOW+CLOSE)/3*VOLUME:0),14)))',
        'description': 'volume high 100d',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 100,
        'source_id': 128,
    },
    'close_12d_2': {
        'formula': 'SUM((CLOSE-DELAY(CLOSE,1)<0?ABS(CLOSE-DELAY(CLOSE,1)):0),12)',
        'description': 'close 12d 2',
        'columns': ['close'],
        'warmup_bars': 12,
        'source_id': 129,
    },
    'decay_corr_rank_volume_vwap_40d_3': {
        'formula': '(RANK(DECAYLINEAR(CORR(((HIGH+LOW)/2),MEAN(VOLUME,40),9),10))/RANK(DECAYLINEAR(CORR(RANK(VWAP),RANK(VOLUME),7),3)))',
        'description': 'decay corr rank volume vwap 40d 3',
        'columns': ['high', 'low', 'volume'],
        'warmup_bars': 40,
        'source_id': 130,
    },
    'corr_ts_rank_rank_volume_vwap_50d': {
        'formula': '(RANK(DELTA(VWAP,1))^TSRANK(CORR(CLOSE,MEAN(VOLUME,50),18),18))',
        'description': 'corr ts rank rank volume vwap 50d',
        'columns': ['close', 'volume'],
        'warmup_bars': 50,
        'source_id': 131,
    },
    'average_amount': {
        'formula': 'MEAN(AMOUNT,20)',
        'description': 'average amount',
        'columns': ['amount'],
        'warmup_bars': 20,
        'source_id': 132,
    },
    'high_low_age_gap': {
        'formula': '((20-HIGHDAY(HIGH,20))/20)*100-((20-LOWDAY(LOW,20))/20)*100',
        'description': 'high low age gap',
        'columns': ['high', 'low'],
        'warmup_bars': 100,
        'source_id': 133,
    },
    'smooth_close_20d': {
        'formula': 'SMA(DELAY(CLOSE/DELAY(CLOSE,20),1),20,1)',
        'description': 'smooth close 20d',
        'columns': ['close'],
        'warmup_bars': 20,
        'source_id': 135,
    },
    'corr_rank_volume_return_10d': {
        'formula': '((-1*RANK(DELTA(RET,3)))*CORR(OPEN,VOLUME,10))',
        'description': 'corr rank volume return 10d',
        'columns': ['close', 'open', 'volume'],
        'warmup_bars': 10,
        'source_id': 136,
    },
    'open_high_16d': {
        'formula': '16*(CLOSE-DELAY(CLOSE,1)+(CLOSE-OPEN)/2+DELAY(CLOSE,1)-DELAY(OPEN,1))/((ABS(HIGH-DELAY(CLOSE,1))>ABS(LOW-DELAY(CLOSE,1))&ABS(HIGH-DELAY(CLOSE,1))>ABS(HIGH-DELAY(LOW,1))?ABS(HIGH-DELAY(CLOSE,1))+ABS(LOW-DELAY(CLOSE,1))/2+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4:(ABS(LOW-DELAY(CLOSE,1))>ABS(HIGH-DELAY(LOW,1))&ABS(LOW-DELAY(CLOSE,1))>ABS(HIGH-DELAY(CLOSE,1))?ABS(LOW-DELAY(CLOSE,1))+ABS(HIGH-DELAY(CLOSE,1))/2+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4:ABS(HIGH-DELAY(LOW,1))+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4)))*MAX(ABS(HIGH-DELAY(CLOSE,1)),ABS(LOW-DELAY(CLOSE,1)))',
        'description': 'open high 16d',
        'columns': ['close', 'high', 'low', 'open'],
        'warmup_bars': 16,
        'source_id': 137,
    },
    'decay_corr_ts_rank_volume_vwap_60d': {
        'formula': '((RANK(DECAYLINEAR(DELTA((((LOW*0.7)+(VWAP*0.3))),3),20))-TSRANK(DECAYLINEAR(TSRANK(CORR(TSRANK(LOW,8),TSRANK(MEAN(VOLUME,60),17),5),19),16),7))*-1)',
        'description': 'decay corr ts rank volume vwap 60d',
        'columns': ['low', 'volume'],
        'warmup_bars': 60,
        'source_id': 138,
    },
    'open_volume_corr': {
        'formula': '(-1*CORR(OPEN,VOLUME,10))',
        'description': 'open volume corr',
        'columns': ['open', 'volume'],
        'warmup_bars': 10,
        'source_id': 139,
    },
    'decay_corr_ts_rank_volume_open_60d': {
        'formula': 'MIN(RANK(DECAYLINEAR(((RANK(OPEN)+RANK(LOW))-(RANK(HIGH)+RANK(CLOSE))),8)),TSRANK(DECAYLINEAR(CORR(TSRANK(CLOSE,8),TSRANK(MEAN(VOLUME,60),20),8),7),3))',
        'description': 'decay corr ts rank volume open 60d',
        'columns': ['close', 'high', 'low', 'open', 'volume'],
        'warmup_bars': 60,
        'source_id': 140,
    },
    'corr_rank_volume_high_15d': {
        'formula': '(RANK(CORR(RANK(HIGH),RANK(MEAN(VOLUME,15)),9))*-1)',
        'description': 'corr rank volume high 15d',
        'columns': ['high', 'volume'],
        'warmup_bars': 15,
        'source_id': 141,
    },
    'ts_rank_rank_volume_close_20d_5': {
        'formula': '(((-1*RANK(TSRANK(CLOSE,10)))*RANK(DELTA(DELTA(CLOSE,1),1)))*RANK(TSRANK((VOLUME/MEAN(VOLUME,20)),5)))',
        'description': 'ts rank rank volume close 20d 5',
        'columns': ['close', 'volume'],
        'warmup_bars': 20,
        'source_id': 142,
    },
    'close_1d': {
        'formula': 'CLOSE>DELAY(CLOSE,1)?(CLOSE-DELAY(CLOSE,1))/DELAY(CLOSE,1)*SELF:SELF',
        'description': 'close 1d',
        'columns': ['close'],
        'warmup_bars': 1,
        'source_id': 143,
    },
    'down_day_impact': {
        'formula': 'SUMIF(ABS(CLOSE/DELAY(CLOSE,1)-1)/AMOUNT,20,CLOSE<DELAY(CLOSE,1))/COUNT(CLOSE<DELAY(CLOSE,1),20)',
        'description': 'down day impact',
        'columns': ['amount', 'close'],
        'warmup_bars': 20,
        'source_id': 144,
    },
    'volume_mean_gap': {
        'formula': '(MEAN(VOLUME,9)-MEAN(VOLUME,26))/MEAN(VOLUME,12)*100',
        'description': 'volume mean gap',
        'columns': ['volume'],
        'warmup_bars': 100,
        'source_id': 145,
    },
    'corr_rank_volume_open_60d': {
        'formula': '((RANK(CORR((OPEN),SUM(MEAN(VOLUME,60),9),6))<RANK((OPEN-TSMIN(OPEN,14))))*-1)',
        'description': 'corr rank volume open 60d',
        'columns': ['open', 'volume'],
        'warmup_bars': 60,
        'source_id': 148,
    },
    'typical_price_volume': {
        'formula': '(CLOSE+HIGH+LOW)/3*VOLUME',
        'description': 'typical price volume',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 3,
        'source_id': 150,
    },
    'smooth_close_26d': {
        'formula': 'SMA(MEAN(DELAY(SMA(DELAY(CLOSE/DELAY(CLOSE,9),1),9,1),1),12)-MEAN(DELAY(SMA(DELAY(CLOSE/DELAY(CLOSE,9),1),9,1),1),26),9,1)',
        'description': 'smooth close 26d',
        'columns': ['close'],
        'warmup_bars': 26,
        'source_id': 152,
    },
    'close_24d_4': {
        'formula': '(MEAN(CLOSE,3)+MEAN(CLOSE,6)+MEAN(CLOSE,12)+MEAN(CLOSE,24))/4',
        'description': 'close 24d 4',
        'columns': ['close'],
        'warmup_bars': 24,
        'source_id': 153,
    },
    'corr_volume_vwap_180d': {
        'formula': '(((VWAP-MIN(VWAP,16)))<(CORR(VWAP,MEAN(VOLUME,180),18)))',
        'description': 'corr volume vwap 180d',
        'columns': ['volume'],
        'warmup_bars': 180,
        'source_id': 154,
    },
    'smooth_volume_27d': {
        'formula': 'SMA(VOLUME,13,2)-SMA(VOLUME,27,2)-SMA(SMA(VOLUME,13,2)-SMA(VOLUME,27,2),10,2)',
        'description': 'smooth volume 27d',
        'columns': ['volume'],
        'warmup_bars': 27,
        'source_id': 155,
    },
    'decay_rank_vwap_open_5d': {
        'formula': '(MAX(RANK(DECAYLINEAR(DELTA(VWAP,5),3)),RANK(DECAYLINEAR(((DELTA(((OPEN*0.15)+(LOW*0.85)),2)/((OPEN*0.15)+(LOW*0.85)))*-1),3)))*-1)',
        'description': 'decay rank vwap open 5d',
        'columns': ['low', 'open'],
        'warmup_bars': 5,
        'source_id': 156,
    },
    'ts_rank_rank_return_close_6d': {
        'formula': '(MIN(PROD(RANK(RANK(LOG(SUM(TSMIN(RANK(RANK((-1*RANK(DELTA((CLOSE-1),5))))),2),1)))),1),5)+TSRANK(DELAY((-1*RET),6),5))',
        'description': 'ts rank rank return close 6d',
        'columns': ['close'],
        'warmup_bars': 6,
        'source_id': 157,
    },
    'smooth_high_low_15d': {
        'formula': '((HIGH-SMA(CLOSE,15,2))-(LOW-SMA(CLOSE,15,2)))/CLOSE',
        'description': 'smooth high low 15d',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 15,
        'source_id': 158,
    },
    'high_low_100d_24': {
        'formula': '((CLOSE-SUM(MIN(LOW,DELAY(CLOSE,1)),6))/SUM(MAX(HIGH,DELAY(CLOSE,1))-MIN(LOW,DELAY(CLOSE,1)),6)*12*24+(CLOSE-SUM(MIN(LOW,DELAY(CLOSE,1)),12))/SUM(MAX(HIGH,DELAY(CLOSE,1))-MIN(LOW,DELAY(CLOSE,1)),12)*6*24+(CLOSE-SUM(MIN(LOW,DELAY(CLOSE,1)),24))/SUM(MAX(HIGH,DELAY(CLOSE,1))-MIN(LOW,DELAY(CLOSE,1)),24)*6*24)*100/(6*12+6*24+12*24)',
        'description': 'high low 100d 24',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 100,
        'source_id': 159,
    },
    'smooth_volatility_close_20d': {
        'formula': 'SMA((CLOSE<=DELAY(CLOSE,1)?STD(CLOSE,20):0),20,1)',
        'description': 'smooth volatility close 20d',
        'columns': ['close'],
        'warmup_bars': 20,
        'source_id': 160,
    },
    'mean_true_range': {
        'formula': 'MEAN(MAX(MAX((HIGH-LOW),ABS(DELAY(CLOSE,1)-HIGH)),ABS(DELAY(CLOSE,1)-LOW)),12)',
        'description': 'mean true range',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 12,
        'source_id': 161,
    },
    'smooth_close_100d': {
        'formula': '(SMA(MAX(CLOSE-DELAY(CLOSE,1),0),12,1)/SMA(ABS(CLOSE-DELAY(CLOSE,1)),12,1)*100-MIN(SMA(MAX(CLOSE-DELAY(CLOSE,1),0),12,1)/SMA(ABS(CLOSE-DELAY(CLOSE,1)),12,1)*100,12))/(MAX(SMA(MAX(CLOSE-DELAY(CLOSE,1),0),12,1)/SMA(ABS(CLOSE-DELAY(CLOSE,1)),12,1)*100,12)-MIN(SMA(MAX(CLOSE-DELAY(CLOSE,1),0),12,1)/SMA(ABS(CLOSE-DELAY(CLOSE,1)),12,1)*100,12))',
        'description': 'smooth close 100d',
        'columns': ['close'],
        'warmup_bars': 100,
        'source_id': 162,
    },
    'rank_volume_vwap_20d': {
        'formula': 'RANK(((((-1*RET)*MEAN(VOLUME,20))*VWAP)*(HIGH-CLOSE)))',
        'description': 'rank volume vwap 20d',
        'columns': ['close', 'high', 'volume'],
        'warmup_bars': 20,
        'source_id': 163,
    },
    'smooth_high_low_100d_13': {
        'formula': 'SMA((((CLOSE>DELAY(CLOSE,1))?1/(CLOSE-DELAY(CLOSE,1)):1)-MIN(((CLOSE>DELAY(CLOSE,1))?1/(CLOSE-DELAY(CLOSE,1)):1),12))/(HIGH-LOW)*100,13,2)',
        'description': 'smooth high low 100d 13',
        'columns': ['close', 'high', 'low'],
        'warmup_bars': 100,
        'source_id': 164,
    },
    'close_12d_3': {
        'formula': 'SUM((CLOSE-DELAY(CLOSE,1)>0?CLOSE-DELAY(CLOSE,1):0),12)',
        'description': 'close 12d 3',
        'columns': ['close'],
        'warmup_bars': 12,
        'source_id': 167,
    },
    'relative_volume': {
        'formula': '(-1*VOLUME/MEAN(VOLUME,20))',
        'description': 'relative volume',
        'columns': ['volume'],
        'warmup_bars': 20,
        'source_id': 168,
    },
    'smooth_close_26d_10': {
        'formula': 'SMA(MEAN(DELAY(SMA(CLOSE-DELAY(CLOSE,1),9,1),1),12)-MEAN(DELAY(SMA(CLOSE-DELAY(CLOSE,1),9,1),1),26),10,1)',
        'description': 'smooth close 26d 10',
        'columns': ['close'],
        'warmup_bars': 26,
        'source_id': 169,
    },
    'rank_volume_vwap_20d_5': {
        'formula': '((((RANK((1/CLOSE))*VOLUME)/MEAN(VOLUME,20))*((HIGH*RANK((HIGH-CLOSE)))/(SUM(HIGH,5)/5)))-RANK((VWAP-DELAY(VWAP,5))))',
        'description': 'rank volume vwap 20d 5',
        'columns': ['close', 'high', 'volume'],
        'warmup_bars': 20,
        'source_id': 170,
    },
    'intraday_wick_leverage': {
        'formula': '((-1*((LOW-CLOSE)*(OPEN^5)))/((CLOSE-HIGH)*(CLOSE^5)))',
        'description': 'intraday wick leverage',
        'columns': ['close', 'high', 'low', 'open'],
        'warmup_bars': 5,
        'source_id': 171,
    },
    'price_volume_100d': {
        'formula': 'MEAN(ABS(SUM((LD>0&LD>HD)?LD:0,14)*100/SUM(TR,14)-SUM((HD>0&HD>LD)?HD:0,14)*100/SUM(TR,14))/(SUM((LD>0&LD>HD)?LD:0,14)*100/SUM(TR,14)+SUM((HD>0&HD>LD)?HD:0,14)*100/SUM(TR,14))*100,6)',
        'description': 'price volume 100d',
        'columns': ['close', 'high', 'low', 'open'],
        'warmup_bars': 100,
        'source_id': 172,
    },
    'smooth_close_13d_13': {
        'formula': '3*SMA(CLOSE,13,2)-2*SMA(SMA(CLOSE,13,2),13,2)+SMA(SMA(SMA(LOG(CLOSE),13,2),13,2),13,2)',
        'description': 'smooth close 13d 13',
        'columns': ['close'],
        'warmup_bars': 13,
        'source_id': 173,
    },
    'smooth_volatility_close_20d_20': {
        'formula': 'SMA((CLOSE>DELAY(CLOSE,1)?STD(CLOSE,20):0),20,1)',
        'description': 'smooth volatility close 20d 20',
        'columns': ['close'],
        'warmup_bars': 20,
        'source_id': 174,
    },
    'corr_smooth_rank_volume_high_12d': {
        'formula': 'CORR(RANK(((CLOSE-TSMIN(LOW,12))/(TSMAX(HIGH,12)-TSMIN(LOW,12)))),RANK(VOLUME),6)',
        'description': 'corr smooth rank volume high 12d',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 12,
        'source_id': 176,
    },
    'days_since_high_share': {
        'formula': '((20-HIGHDAY(HIGH,20))/20)*100',
        'description': 'days since high share',
        'columns': ['high'],
        'warmup_bars': 100,
        'source_id': 177,
    },
    'corr_rank_volume_vwap_50d': {
        'formula': '(RANK(CORR(VWAP,VOLUME,4))*RANK(CORR(RANK(LOW),RANK(MEAN(VOLUME,50)),12)))',
        'description': 'corr rank volume vwap 50d',
        'columns': ['low', 'volume'],
        'warmup_bars': 50,
        'source_id': 179,
    },
    'corr_rank_open_close_200d': {
        'formula': '(RANK(CORR(DELAY((OPEN-CLOSE),1),CLOSE,200))+RANK((OPEN-CLOSE)))',
        'description': 'corr rank open close 200d',
        'columns': ['close', 'open'],
        'warmup_bars': 200,
        'source_id': 184,
    },
    'open_close_gap_square': {
        'formula': 'RANK((-1*((1-(OPEN/CLOSE))^2)))',
        'description': 'open close gap square',
        'columns': ['close', 'open'],
        'warmup_bars': 2,
        'source_id': 185,
    },
    'price_volume_100d_6': {
        'formula': '(MEAN(ABS(SUM((LD>0&LD>HD)?LD:0,14)*100/SUM(TR,14)-SUM((HD>0&HD>LD)?HD:0,14)*100/SUM(TR,14))/(SUM((LD>0&LD>HD)?LD:0,14)*100/SUM(TR,14)+SUM((HD>0&HD>LD)?HD:0,14)*100/SUM(TR,14))*100,6)+DELAY(MEAN(ABS(SUM((LD>0&LD>HD)?LD:0,14)*100/SUM(TR,14)-SUM((HD>0&HD>LD)?HD:0,14)*100/SUM(TR,14))/(SUM((LD>0&LD>HD)?LD:0,14)*100/SUM(TR,14)+SUM((HD>0&HD>LD)?HD:0,14)*100/SUM(TR,14))*100,6),6))/2',
        'description': 'price volume 100d 6',
        'columns': ['close', 'high', 'low', 'open'],
        'warmup_bars': 100,
        'source_id': 186,
    },
    'open_high_20d_2': {
        'formula': 'SUM((OPEN<=DELAY(OPEN,1)?0:MAX((HIGH-OPEN),(OPEN-DELAY(OPEN,1)))),20)',
        'description': 'open high 20d 2',
        'columns': ['high', 'open'],
        'warmup_bars': 20,
        'source_id': 187,
    },
    'smooth_high_low_100d_100': {
        'formula': '((HIGH-LOW-SMA(HIGH-LOW,11,2))/SMA(HIGH-LOW,11,2))*100',
        'description': 'smooth high low 100d 100',
        'columns': ['high', 'low'],
        'warmup_bars': 100,
        'source_id': 188,
    },
    'close_mean_absolute_deviation': {
        'formula': 'MEAN(ABS(CLOSE-MEAN(CLOSE,6)),6)',
        'description': 'close mean absolute deviation',
        'columns': ['close'],
        'warmup_bars': 6,
        'source_id': 189,
    },
    'conditional_sum_day_count_close_20d': {
        'formula': 'LOG((COUNT(CLOSE/DELAY(CLOSE)-1>((CLOSE/DELAY(CLOSE,19))^(1/20)-1),20)-1)*(SUMIF(((CLOSE/DELAY(CLOSE)-1-(CLOSE/DELAY(CLOSE,19))^(1/20)-1))^2,20,CLOSE/DELAY(CLOSE)-1<(CLOSE/DELAY(CLOSE,19))^(1/20)-1))/((COUNT((CLOSE/DELAY(CLOSE)-1<(CLOSE/DELAY(CLOSE,19))^(1/20)-1),20))*(SUMIF((CLOSE/DELAY(CLOSE)-1-((CLOSE/DELAY(CLOSE,19))^(1/20)-1))^2,20,CLOSE/DELAY(CLOSE)-1>(CLOSE/DELAY(CLOSE,19))^(1/20)-1))))',
        'description': 'conditional sum day count close 20d',
        'columns': ['close'],
        'warmup_bars': 20,
        'source_id': 190,
    },
    'volume_low_corr_mid_gap': {
        'formula': '((CORR(MEAN(VOLUME,20),LOW,5)+((HIGH+LOW)/2))-CLOSE)',
        'description': 'volume low corr mid gap',
        'columns': ['close', 'high', 'low', 'volume'],
        'warmup_bars': 20,
        'source_id': 191,
    },
}

SKIPPED_SIMILAR_SOURCE_IDS = ((68, 9), (147, 21), (151, 24), (72, 47), (82, 47), (58, 53), (67, 63), (79, 63))

